### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mattl** [rdegges/okta-flask-example#1]
Hey, can you please put a license on this repo?

**Comment by KyeRussell** [comment]
+1 would thumbs up again

**Comment by rdegges** [comment]
Heyo. It's licensed already under public domain -- if you look in the packaging file you can see it listed as a classifier. I'll go ahead and add UNLICENSE as well.

This is the most liberal possible license so you can do whatever you want with it: copy it, say you wrote it, take a piece of it, use it entirely without attribution, don't copy the license, whatever. I don't care =p Just have fun.
